# Generated by Django 4.1.3 on 2023-01-24 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('departament_id', models.AutoField(primary_key=True, serialize=False)),
                ('departament', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user_id', models.IntegerField(default=199999, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=5)),
                ('teacher', models.IntegerField()),
                ('theme', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('departament', models.ForeignKey(default=199999, on_delete=django.db.models.deletion.CASCADE, to='app.departaments')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudents',
            fields=[
                ('teacherstudent_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.ForeignKey(default=199999, on_delete=django.db.models.deletion.CASCADE, to='app.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersThemes',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=60)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentGroups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=5)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departaments')),
            ],
        ),
    ]
