# Generated by Django 4.1.3 on 2023-01-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_departaments_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.IntegerField(default=199999),
        ),
    ]
