# Generated by Django 4.1.3 on 2023-01-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_students_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='teacher',
            field=models.ForeignKey(default=199999, on_delete=django.db.models.deletion.CASCADE, to='app.teachers'),
        ),
    ]
