# Generated by Django 4.1.3 on 2023-01-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_students_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersthemes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teachers'),
        ),
    ]
