# Generated by Django 4.1.3 on 2023-01-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_teachersthemes_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='theme_status',
            field=models.CharField(default='Очікується підтвердження', max_length=30),
        ),
    ]
